# Generated by Django 5.0.6 on 2024-07-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carretas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frota', models.CharField(max_length=150, verbose_name='Frota')),
                ('placa', models.CharField(max_length=150, verbose_name='Placa')),
                ('motorista', models.CharField(max_length=250, verbose_name='Motorista padrão')),
                ('renavam', models.CharField(max_length=250, verbose_name='Renavam')),
                ('anomod', models.CharField(choices=[('A', '2024/2024'), ('B', '2023/2024'), ('C', '2022/2023'), ('D', '2021/2022'), ('E', '2020/2021'), ('F', '2019/2020'), ('G', '2018/2019'), ('H', '2017/2018'), ('H', '2016/2017'), ('H', '2015/2016'), ('H', '2014/2015'), ('H', '2013/2014'), ('H', '2012/2013'), ('H', '2011/2012'), ('H', '2010/2011'), ('H', '2009/2010'), ('H', '2008/2009'), ('H', '2007/2008'), ('H', '2006/2007'), ('H', '2005/2006'), ('H', '2004/2005')], max_length=1, verbose_name='Ano / Modelo')),
                ('cor', models.CharField(choices=[('A', 'Amarela'), ('A', 'Azul'), ('B', 'Branca'), ('C', 'Cinza'), ('P', 'Prata'), ('P', 'Preta'), ('V', 'Vermelho')], max_length=1, verbose_name='Cor')),
                ('chassi', models.CharField(max_length=150, verbose_name='Chassi')),
                ('crlv', models.CharField(choices=[('A', 'Araucária')], max_length=1, verbose_name='CRLV')),
                ('marca', models.CharField(choices=[('B', 'BIASI'), ('F', 'FACCHINI'), ('G', 'GOTTI'), ('K', 'KRONORTE'), ('M', 'METALESP'), ('R', 'R/TRIEL'), ('R', 'RANDON'), ('R', 'RECRUSUL'), ('R', 'RHODOSS'), ('R', 'RODOTEC'), ('R', 'RODOTÉCNICA'), ('R', 'RODOTIC'), ('T', 'TRIEL')], max_length=1, verbose_name='Marca')),
                ('modelo', models.CharField(choices=[('B', 'BITREM DIANTEIRO'), ('B', 'BITREM TRASEIRO'), ('Q', 'QUATRO PATAS'), ('R', 'RODOTREM DIANTEIRO'), ('R', 'RODOTREM TRASEIRO'), ('V', 'VANDERLÉIA')], max_length=1, verbose_name='Modelo')),
                ('eixos', models.CharField(choices=[('A', '2'), ('B', '3'), ('C', '4')], max_length=1, verbose_name='Eixos')),
                ('pneus', models.CharField(choices=[('A', '295/80'), ('B', 'Single')], max_length=1, verbose_name='Pneus')),
                ('suspensao', models.CharField(choices=[('M', 'Mecânica'), ('P', 'Pneumática')], max_length=1, verbose_name='Suspensão')),
                ('altura', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Altura')),
                ('pbt', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='PBT')),
                ('toneladas', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Toneladas')),
                ('litros', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Litros')),
                ('tipo', models.CharField(choices=[('A', 'A.CARB'), ('A', 'ALUM'), ('B', 'BASC'), ('I', 'INOX'), ('L', 'LS'), ('T', 'TERM')], max_length=1, verbose_name='Tipo')),
                ('tara', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Tara')),
                ('suspensor', models.CharField(choices=[('A', '1°'), ('B', '1°, 2°'), ('C', '1°, 2°, 3°'), ('D', '1°, 2°, 4°'), ('E', '1°, 3°')], max_length=1, verbose_name='Suspensor eixos')),
                ('bolsa', models.CharField(max_length=150, verbose_name='Bolsa suspensor')),
                ('mola', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, verbose_name='Mola pneumática')),
                ('locada', models.CharField(max_length=150, verbose_name='Locada')),
                ('transportadora', models.CharField(choices=[('V', 'VIA DUPLA')], max_length=1, verbose_name='Transportadora')),
                ('notafiscal', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, verbose_name='Nota fiscal')),
                ('status', models.CharField(max_length=150, verbose_name='Status')),
            ],
        ),
    ]
