# Generated by Django 5.0.6 on 2024-07-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carretas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(

            name='Acessorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placaacc', models.CharField(max_length=150, verbose_name='Placa')),
                ('bottomclaro', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, verbose_name='Bottom claro')),
                ('bottomescuro', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, verbose_name='Bottom escuro')),
                ('bottomtepar', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, verbose_name='Bottom Tepar')),
                ('api', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, verbose_name='API')),
                ('descarga', models.CharField(choices=[('A', '1T'), ('B', '2T'), ('C', '2T ISOLADO'), ('D', 'Não')], max_length=1, verbose_name='Enc. Descarga')),
                ('dreno', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, verbose_name='Reg. No dreno')),
                ('graudbolt', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, verbose_name='Graud bolt Itajaí')),
                ('olhodegato', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, verbose_name='Olho de gato')),
                ('mangote', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, verbose_name='Mangote')),
                ('macarico', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, verbose_name='Maçarico')),
            ],
        ),
    ]
