# Generated by Django 5.0.6 on 2024-07-22 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carretas', '0002_acessorios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acessorios',
            name='placaacc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carretas.carretas', to_field='placa', verbose_name='Placa'),
        ),
        migrations.AlterField(
            model_name='carretas',
            name='anomod',
            field=models.CharField(choices=[('A', '2024/2024'), ('B', '2023/2024'), ('C', '2022/2023'), ('D', '2021/2022'), ('E', '2020/2021'), ('F', '2019/2020'), ('G', '2018/2019'), ('H', '2017/2018'), ('I', '2016/2017'), ('J', '2015/2016'), ('K', '2014/2015'), ('L', '2013/2014'), ('M', '2012/2013'), ('N', '2011/2012'), ('O', '2010/2011'), ('P', '2009/2010'), ('Q', '2008/2009'), ('R', '2007/2008'), ('S', '2006/2007'), ('T', '2005/2006'), ('U', '2004/2005')], max_length=1, verbose_name='Ano / Modelo'),
        ),
        migrations.AlterField(
            model_name='carretas',
            name='cor',
            field=models.CharField(choices=[('A', 'Amarela'), ('B', 'Azul'), ('C', 'Branca'), ('D', 'Cinza'), ('E', 'Prata'), ('F', 'Preta'), ('G', 'Vermelho')], max_length=1, verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='carretas',
            name='marca',
            field=models.CharField(choices=[('B', 'BIASI'), ('F', 'FACCHINI'), ('G', 'GOTTI'), ('K', 'KRONORTE'), ('M', 'METALESP'), ('R', 'R/TRIEL'), ('S', 'RANDON'), ('T', 'RECRUSUL'), ('U', 'RHODOSS'), ('V', 'RODOTEC'), ('W', 'RODOTÉCNICA'), ('X', 'RODOTIC'), ('Y', 'TRIEL')], max_length=1, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='carretas',
            name='modelo',
            field=models.CharField(choices=[('B', 'BITREM DIANTEIRO'), ('C', 'BITREM TRASEIRO'), ('D', 'QUATRO PATAS'), ('E', 'RODOTREM DIANTEIRO'), ('F', 'RODOTREM TRASEIRO'), ('G', 'VANDERLÉIA')], max_length=1, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='carretas',
            name='placa',
            field=models.CharField(max_length=150, unique=True, verbose_name='Placa'),
        ),
        migrations.AlterField(
            model_name='carretas',
            name='tipo',
            field=models.CharField(choices=[('A', 'A.CARB'), ('B', 'ALUM'), ('C', 'BASC'), ('D', 'INOX'), ('E', 'LS'), ('F', 'TERM')], max_length=1, verbose_name='Tipo'),
        ),
    ]
