# Generated by Django 5.0.6 on 2024-07-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cavalos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frota', models.CharField(max_length=150, verbose_name='Frota')),
                ('placa', models.CharField(max_length=150, verbose_name='Placa')),
                ('motorista', models.CharField(max_length=150, verbose_name='Motorista padrão')),
                ('renavam', models.CharField(max_length=150, verbose_name='Renavam')),
                ('anomod', models.CharField(choices=[('A', '2024/2024'), ('B', '2023/2024'), ('C', '2022/2023'), ('D', '2021/2022'), ('E', '2020/2021'), ('F', '2019/2020'), ('G', '2018/2019'), ('H', '2017/2018')], max_length=1, verbose_name='Ano / Modelo')),
                ('cor', models.CharField(choices=[('B', 'Branco'), ('P', 'Preto'), ('V', 'Verde'), ('V', 'Vermelho')], max_length=1, verbose_name='Cor')),
                ('chassi', models.CharField(max_length=150, verbose_name='Chassi')),
                ('crlv', models.CharField(max_length=150, verbose_name='CRLV')),
                ('marca', models.CharField(choices=[('D', 'DAF'), ('S', 'Scania'), ('V', 'Volvo')], max_length=1, verbose_name='Marca')),
                ('modelo', models.CharField(choices=[('R', 'R 450'), ('F', 'FH 460'), ('F', 'FH 540')], max_length=1, verbose_name='Modelo')),
                ('suspensao', models.CharField(choices=[('M', 'Mecânica'), ('P', 'Pneumática')], max_length=1, verbose_name='Suspensão')),
                ('tracao', models.CharField(choices=[('2', '6x2'), ('4', '6x4')], max_length=1, verbose_name='Tração')),
                ('altura', models.CharField(max_length=150, verbose_name='Altura')),
                ('capdiesel', models.CharField(max_length=150, verbose_name='Cap.Diesel')),
                ('pbt', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='PBT')),
                ('tara', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Tara')),
                ('locado', models.CharField(choices=[('A', 'Araucária'), ('C', 'Canoas'), ('C', 'Cubatão'), ('I', 'Itajaí'), ('P', 'Paulínia')], max_length=1, verbose_name='Locado')),
                ('macaricoele', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, verbose_name='Maçarico eletrônico')),
                ('bombadeasfalto', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, verbose_name='Bomba de asfalto')),
                ('bombahidraulica', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, verbose_name='Bomba Hidráulica')),
                ('esperatforca', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, verbose_name='Espera T.Força')),
                ('placasolar', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, verbose_name='Placa solar')),
                ('status', models.CharField(choices=[('A', 'Agregado'), ('O', 'Operação'), ('V', 'Vendido')], max_length=1, verbose_name='Status')),
                ('bloqueador', models.CharField(choices=[('A', 'Antigo cirio'), ('M', 'Moderno cirio'), ('I', 'Ingomar')], max_length=1, verbose_name='Bloqueador')),
                ('transportadora', models.CharField(choices=[('A', 'VIA AVANT'), ('D', 'VIA DUPLA'), ('G', 'GOTTA LTDA'), ('R', 'MR LTDA'), ('R', 'R.J.M Andrade')], max_length=1, verbose_name='Transportadora')),
                ('notafiscal', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, verbose_name='Nota fiscal')),
                ('velocidade', models.CharField(choices=[('F', 'FMS'), ('G', 'GPS'), ('M', 'MAXTRACK'), ('T', 'TAC')], max_length=1, verbose_name='Velocidade')),
                ('fimdegarantia', models.CharField(default='00/00/2024', max_length=150, verbose_name='Fim De Garantia (Altere a data!)')),
                ('dataentregatecnica', models.CharField(default='00/00/2024', max_length=150, verbose_name='Data Entrega Técnica (Altere a data!)')),
            ],
        ),
    ]
